arch: 
  - arm64
  - amd64
services:
  - docker
script: |
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t stenwt/laminar:latest --push -f docker/Dockerfile .
