arch: 
  - arm64
  - amd64
services:
  - docker
before_install:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: docker build -t $DOCKER_USERNAME/laminar:$(uname -m) -f docker/Dockerfile . && docker push $DOCKER_USERNAME/laminar:$(uname -m)
